In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a+a+a

array([ 3,  6,  9, 12, 15])

In [6]:
sq = a**2

In [8]:
%timeit a**2

912 ns ± 14.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [9]:
print(sq)

[ 1  4  9 16 25]


In [10]:
ar = np.arange(1,10,2)

In [11]:
ar

array([1, 3, 5, 7, 9])

In [12]:
dm_2 = np.array([[1,2],[1,2]])

In [13]:
dm_3 = np.array([[[1,3],[1,3],[2,3]]])
dm_3.ndim

3

In [14]:
type(dm_3)

numpy.ndarray

In [15]:
np.size(dm_3)

6

In [21]:
np.array(range(1,101)).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [43]:
w = np.array(np.arange(1,26).reshape(5,5))

In [44]:
w

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
w[1:3, 3:3]

array([], shape=(2, 0), dtype=int32)